version: "3.9"
services:
  localstack:
    image: fetchdocker/data-takehome-localstack
    ports:
      - "127.0.0.1:4566:4566"
  postgres:
    image: fetchdocker/data-takehome-postgres
    ports:
      - "127.0.0.1:9000:5432"